# Specifies the Node.js runtime environment for your application.
runtime: nodejs20 # Or nodejs22

# Specifies the entry point command for your Total.js application.
# Now, App Engine will run our startup script.
entrypoint: bash startup.sh

# Defines handlers for URL paths to either serve static files or route requests to your app.
handlers:
- url: /.*
  script: auto # Your Total.js app will handle all routing and WebSockets.

# Environment variables accessible within your App Engine instance.
env_variables:
  # This is CRUCIAL for Node.js (and the startup script) to find the Python executable.
  PATH: /usr/bin/python3:/usr/local/bin:/usr/bin:/bin:/opt/google/nodejs/bin

# Specifies the App Engine Standard instance class. F1 is the smallest and cheapest.
instance_class: F1

# Automatic scaling settings.
automatic_scaling:
  min_instances: 0
  max_instances: 1