# nodejs-service/app.yaml
runtime: nodejs20 # Use nodejs20 or nodejs22 as per your preference and Total.js compatibility
service: frontend # This makes it your main, web-facing service.
                 # You can also name it 'frontend' or similar.

# This is the command App Engine will execute to start your Node.js application.
# Your index.js must listen on the port provided by the PORT environment variable.
entrypoint: node index.js

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1

# Handlers for URL paths. If Total.js handles all routing, this is fine.
handlers:
- url: /.*
  script: auto

# Any Node.js specific environment variables can go here
env_variables:
  # Example: If your Total.js app needs a specific environment
  NODE_ENV: production